---
- hosts: all
  remote_user: sysreport
  tasks:
     - name: Copy File From Host
       copy:
        src: /tmp/node_exporter-0.18.1.linux-amd64.tar.gz
        dest: /tmp
        mode: "0777"
        remote_src: no
     - name: Extract files
       unarchive:
        src: /tmp/node_exporter-0.18.1.linux-amd64.tar.gz
        dest: /tmp
        mode: "0777"
     - name: Move extracted files
       command: mv -f /tmp/node_exporter-0.18.1.linux-amd64 /var/lib/node_exporter
       arg:
        creates: /var/lib/node_exporter
     - name: Create a systemd service for node_exporter
       file:
        path: /etc/systemd/system/node_exporter.service
        state: touch
        owner: root
        group: root
        mode: "0700"
     - name: Edit Text in File
       blockinfile:
        path: /etc/systemd/system/node_exporter.service
        block: |
         [Unit]
         Description=Node Exporter
         Wants=network-online.target
         After=network-online.target

         [Service]
         User=root
         Type=simple
         ExecStart=/var/lib/node_exporter/node_exporter

         [Install]
         WantedBy=multi-user.target
     - name: Enable and start node_exporter service
       systemd:
         name: node_exporter
         state: started
         enabled: yes
     - name: Firewalld Add Port
       firewalld:
         port: 9100/tcp
         permanent: yes
         state: enable
     - name: Stop Zabbix Service
       systemd:
        name: zabbix_agent
        state: stopped
        enabled: no
