global:
  scrape_interval: 60s
  scrape_timeout: 60s
rule_files:
  - /etc/prometheus/alert.rules
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - '192.168.10.10:9093'
scrape_configs:
  - job_name: 'node'
    static_configs:
    - targets: ['192.168.10.10:9100','192.168.10.20:9100']