apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-pv
  namespace: monitoring
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    path: /data
    server: 192.168.10.10
    readOnly: false