apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pvc
  namespace: monitoring
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: prom-pv