apiVersion: v1
kind: PersistentVolume
metadata:
  name: stm-prometheus-nfs-pv
  namespace: lens-metrics
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    path: /tt2_share_streaming_service/k8s-data/prometheus-data
    server: TT2-QUMULO-STM
    readOnly: false