apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stm-prometheus-nfs-pvc
  namespace: lens-metrics
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: stm-prometheus-nfs-pv